// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: {
    name: "Google Chrome",
    profile: "Default",
  },
  rewrite: [{
    match: ({url}) => url.protocol === "http",
    url: {
        protocol: "https"
    }
  }],
  handlers: [
    {
      match: [
        /^https?:\/\/.*youtube\.com\/.*$/,
        /^https?:\/\/.*youtu\.be\/.*$/,
        /^https?:\/\/.*amazon\.co\.uk.*$/,
        /^https?:\/\/.*degiro.*$/,
        /^https?:\/\/.*twitter.*$/,
        /^https?:\/\/.*\.az\/.*$/,
      ],
      browser: {
        name: "Google Chrome",
        profile: "Profile 1",
      }
    },
    {
      match: "open.spotify.com/*",
      browser: "Spotify"
    },
  ]
}
